## Part 1: `Theoretical Question.`

### 1.` What are the different data structures used in Tensorflow?. Give some examples.`

### `In TensorFlow, the two primary data structures are:`

1. **Tensors**: Tensors are the fundamental building blocks in TensorFlow and are similar to multi-dimensional arrays or matrices. They represent data as n-dimensional arrays and are the main data structure used for computations. Tensors can have any number of dimensions (rank) and can hold both numeric and non-numeric data:

2. **Graphs**: TensorFlow uses a computational graph to define and represent the computations that will be performed. The graph consists of nodes that represent operations and tensors representing data. Each node in the graph represents a mathematical operation, and the edges represent the flow of data (tensors) between operations.

In [4]:
#Examples of Tensors:

import tensorflow as tf
#Scalar (0-dimensional tensor):
scalar = tf.constant(5)
#Vector (1-dimensional tensor):
vector = tf.constant([1, 2, 3, 4, 5])
#Matrix (2-dimensional tensor):
matrix = tf.constant([[1, 2], [3, 4]])
#dimensional tensor:
tensor_3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

2023-07-21 15:24:07.655856: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-07-21 15:24:07.728581: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-07-21 15:24:07.730030: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-21 15:24:08.986704: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [7]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

# Define the computational graph
a = tf.constant(2)
b = tf.constant(3)
c = tf.add(a, b)

# Create a TensorFlow session to run the graph
with tf.Session() as sess:
    result = sess.run(c)
    print(result)

Instructions for updating:
non-resource variables are not supported in the long term
5


2023-07-21 15:26:19.480954: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:375] MLIR V1 optimization pass is not enabled


### 2. `How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example`

In TensorFlow, both constants and variables are used to represent data, but they have different characteristics and purposes:

1. **TensorFlow Constant**:

- A TensorFlow constant is an immutable tensor whose value cannot be changed after its creation.
- Once a constant is defined and initialized with a value, it retains that value throughout the computation, and its value remains fixed during the execution of the program.
- Constants are typically used to store fixed values that remain constant throughout the computation.

In [8]:
#Example of TensorFlow Constant:

import tensorflow as tf

# Define a TensorFlow constant
constant_tensor = tf.constant([1, 2, 3])

#In this example, `constant_tensor` is a TensorFlow constant initialized with a 1-dimensional tensor `[1, 2, 3]`.
 #The value of this constant cannot be modified or updated during the computation.

2. **TensorFlow Variable**:

- A TensorFlow variable is a mutable tensor that can hold values that can be updated or changed during the computation.
- Variables are used to store and update model parameters during the training process. They allow the model to learn and adjust its parameters based on the data and optimization algorithm.
- Unlike constants, the value of a variable can be modified using various operations like `assign` or `assign_add`.

In [10]:
#Example of TensorFlow Variable:
import tensorflow as tf

# Define a TensorFlow variable
initial_value = tf.random.normal(shape=(3, 3), mean=0, stddev=1)
variable_tensor = tf.Variable(initial_value)


#In this example, `variable_tensor` is a TensorFlow variable initialized with a 3x3 tensor generated from a normal distribution. 
#The value of this variable can be updated during the computation using the various assignment operations available in TensorFlow.

### 3.` Describe the process of matrix addition, multiplication, and elementDwise operations in TensorFlow.`

In TensorFlow, matrix addition, multiplication, and element-wise operations are essential mathematical operations used for various computations in deep learning and other machine learning tasks. Let's describe each of these operations in detail:

`Matrix Addition:`  Matrix addition is the process of adding corresponding elements of two matrices to create a new matrix with the same shape as the original matrices. For matrix addition to be valid, the two matrices must have the same dimensions (i.e., the same number of rows and columns).

In TensorFlow, matrix addition can be performed using the tf.add() function or the + operator.

`Matrix Multiplication:` Matrix multiplication is the process of multiplying corresponding elements of two matrices and summing them up to create a new matrix with different dimensions. For matrix multiplication to be valid, the number of columns in the first matrix must be equal to the number of rows in the second matrix.

In TensorFlow, matrix multiplication can be performed using the tf.matmul() function or the @ operator.

`Element-wise Operations:` Element-wise operations apply an operation between corresponding elements of two tensors or matrices. These operations are performed element by element without considering the shape of the tensors, and they are commonly used in various mathematical computations.

In TensorFlow, element-wise operations can be performed using corresponding mathematical functions or operators like tf.add(), tf.subtract(), tf.multiply(), tf.divide(), etc.

In summary, matrix addition, multiplication, and element-wise operations are fundamental mathematical operations used in TensorFlow for various computations in deep learning and machine learning. Understanding and utilizing these operations correctly are essential for building and training effective neural networks and other machine learning models.

## Part 2: `Practical Implementation`

In [4]:
import tensorflow as tf

matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])
                                      #Example of Matrix Addition in TensorFlow:
result_add = tf.add(matrix1, matrix2)
result_add_alt = matrix1 + matrix2
                                      #Example of Matrix Multiplication in TensorFlow:
result_mul = tf.matmul(matrix1, matrix2)
result_mul_alt = matrix1 @ matrix2

print(result_add.numpy())
print(result_add_alt.numpy())

print(result_mul.numpy())
print(result_mul_alt.numpy())



2023-07-21 16:37:38.578892: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-07-21 16:37:38.651175: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-07-21 16:37:38.652308: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-21 16:37:39.881494: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [33]:
#Example of Element-wise Operations in TensorFlow:
import tensorflow as tf

tensor1 = tf.constant([1, 2, 3])
tensor2 = tf.constant([4, 5, 6])

result_elementwise_add = tf.add(tensor1, tensor2)

result_elementwise_mul = tf.multiply(tensor1, tensor2)

print(result_elementwise_add.numpy())
print(result_elementwise_mul.numpy())

[5 7 9]
[ 4 10 18]


## Talk 1: `Creating and Manipulating Matrices.`
### 1. Create a normal matrix A with dimensions 3x3, using TensorFlow's random_normal function. Display the values of matrix A.

### 2. Create a Gaussian matrix B with dimensions 4x4, using TensorFlow's truncated_normal function. Display the values of matrix B.

### 3. Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a mean of 2 and a standard deviation of 0.5, using TensorFlow's random.normal function. Display the values of matrix C.

### 4. Perform matrix addition between matrix A and matrix B, and store the result in matrix D.

### 5. Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.

In [34]:
import tensorflow as tf

# 1. Create a normal matrix A with dimensions 3x3, using TensorFlow's random_normal function.
A = tf.random.normal([3, 3])
print("Matrix A:")
print(A)

# 2. Create a Gaussian matrix B with dimensions 3x3 (to match the dimensions of matrix A).
B = tf.random.truncated_normal([3, 3])
print("Matrix B:")
print(B)

# 3. Create a matrix C with dimensions 2x3, where the values are drawn from a normal distribution with a mean of 2 and a standard deviation of 0.5.
C = tf.random.normal([2, 3], mean=2, stddev=0.5)
print("Matrix C:")
print(C)

# 4. Perform matrix addition between matrix A and matrix B, and store the result in matrix D.
D = tf.add(A, B)
print("Matrix D:")
print(D)

# 5. Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.
E = tf.matmul(C, D)
print("Matrix E:")
print(E)

Matrix A:
tf.Tensor(
[[-0.8692205   0.52161187  0.8716782 ]
 [-0.6580834  -1.4340438  -0.13840975]
 [ 2.398869    0.15419838  1.3917272 ]], shape=(3, 3), dtype=float32)
Matrix B:
tf.Tensor(
[[ 1.0836473   0.296019   -0.00317042]
 [ 1.921282    1.4694746  -0.41864824]
 [ 0.48359945  1.6313518   0.17777042]], shape=(3, 3), dtype=float32)
Matrix C:
tf.Tensor(
[[1.7150543 1.7728846 2.6744595]
 [2.452027  1.8459572 2.5308132]], shape=(2, 3), dtype=float32)
Matrix D:
tf.Tensor(
[[ 0.21442676  0.8176309   0.86850774]
 [ 1.2631986   0.03543079 -0.557058  ]
 [ 2.8824685   1.7855502   1.5694976 ]], shape=(3, 3), dtype=float32)
Matrix E:
tf.Tensor(
[[10.316303   6.2404776  4.699496 ]
 [10.15258    6.589151   5.073405 ]], shape=(2, 3), dtype=float32)


## Talk 2: `Performing Additional Matrix Operation.`

### 1. Create a matrix F with dimensions 2x2, initialized with random values using TensorFlow's random_uniform function.

### 2. Calculate the transpose of matrix F and store the result in matrix G.

### 3. Calculate the element-wise exponential of matrix F and store the result in matrix H

### 4. Create a matrix I by concatenating matrix F and matrix G horizontally.

### 5. Create a matrix J by concatenating matrix F and matrix H vertically.

In [35]:
import tensorflow as tf

# 1. Create a matrix F with dimensions 2x2, initialized with random values using TensorFlow's random_uniform function.
F = tf.random.uniform([2, 2])
print("Matrix F:")
print(F)

# 2. Calculate the transpose of matrix F and store the result in matrix G.
G = tf.transpose(F)
print("Matrix G:")
print(G)

# 3. Calculate the element-wise exponential of matrix F and store the result in matrix H.
H = tf.exp(F)
print("Matrix H:")
print(H)

# 4. Create a matrix I by concatenating matrix F and matrix G horizontally.
I = tf.concat([F, G], axis=1)
print("Matrix I:")
print(I)

# 5. Create a matrix J by concatenating matrix F and matrix H vertically.
J = tf.concat([F, H], axis=0)
print("Matrix J:")
print(J)

Matrix F:
tf.Tensor(
[[0.05882573 0.8809929 ]
 [0.58777726 0.34340692]], shape=(2, 2), dtype=float32)
Matrix G:
tf.Tensor(
[[0.05882573 0.58777726]
 [0.8809929  0.34340692]], shape=(2, 2), dtype=float32)
Matrix H:
tf.Tensor(
[[1.0605904 2.4132946]
 [1.799983  1.4097422]], shape=(2, 2), dtype=float32)
Matrix I:
tf.Tensor(
[[0.05882573 0.8809929  0.05882573 0.58777726]
 [0.58777726 0.34340692 0.8809929  0.34340692]], shape=(2, 4), dtype=float32)
Matrix J:
tf.Tensor(
[[0.05882573 0.8809929 ]
 [0.58777726 0.34340692]
 [1.0605904  2.4132946 ]
 [1.799983   1.4097422 ]], shape=(4, 2), dtype=float32)
